### PR TITLE
Fix Cannot read property 'data' of undefined

### PR DESCRIPTION
**Pull request by redvivi**
Fix intermittent error:

```
TypeError: Cannot read property 'data' of undefined
    at /var/task/node_modules/aws-cloudwatch-log/index.js:152:32
```

### CODE REVIEW

**Comment by redvivi** [comment]
Hello @nicolasdao,
I am facing production errors due to undefined property.
Can you please review and merge this into the code base please?

**Comment by redvivi** [comment]
Hello @leandono , @InsidiousForce.
It looks like @nicolasdao is unavailable, can you please proceed?
Thanks.

**Comment by leandono** [comment]
@redvivi I don't have permissions to merge, my suggestion is create a private fork with the fix and install the dependency from there.

**Comment by redvivi** [comment]
Thanks @leandono ! 

That's unfortunate. Unfortunately my 80 implementations using this library is initialised from npm, which I can not publish on.

The easiest way would be to merge and deploy, so it will fix this issue for many users. Do you have any ways to reach out to @nicolasdao ?

**Comment by nicolasdao** [comment]
Hi @redvivi and @leandono ,

I apologise for the late reply and intervention. I've just merged this PR and deployed a new version on NPM (0.1.4).

Many thanks for the effort you put into this PR.

Cheers,

Nic

**Pull request merged**
